version: "3.7"

services: 
  ec2: 
    build: 
        context: .
        dockerfile: Dockerfile.ec2
    container_name: ec2
    ports: 
    - 8888:80
    volumes:
      - ./ec2:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1

  # ec4: 
  #   image: php:7.2-apache
  #   container_name: ec4
  #   ports: 
  #   - 8899:80
  #   volumes:
  #     - ./ec4:/var/www/html
  #   environment:
  #     XDEBUG_CONFIG: remote_host=172.17.0.1

  eccube_db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: eccube_db
    environment:
      - MYSQL_DATABASE=eccube_db
      - MYSQL_USER=root
      - MYQSL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_ROOT_HOST=%

